### ISSUE TITLE
Asteroid Station revival

### ISSUE THREAD

**Issue by CorruptComputer** [CorruptComputer/-tg-station#1]
# TODO:
### General
- [ ] Arrivals
- [ ] Art Storage
- [ ] Auxiliary Tool Storage
- [ ] Emergency Storage
- [ ] Escape Pods
- [ ] Escape Shuttle
- [ ] Escape Shuttle Hallway
- [ ] Garden
- [ ] Primary Tool Storage

### Recreational
- [ ] Bar
- [ ] Chapel
- [ ] Dormitory
- [ ] Holodeck
- [ ] Hydroponics
- [ ] Kitchen and Freezer
- [ ] Library
- [ ] Locker Room
- [ ] Theatre

### Medical
- [ ] Medbay
- [ ] Chemistry Lab
- [ ] Chief Medical Officer's Office
- [ ] Genetics
- [ ] Medbay Storage
- [ ] Morgue
- [ ] Operating Theatre
- [ ] Patient Room
- [ ] Recovery Room
- [ ] Virology

### Logistics
- [ ] Supplies
- [ ] Cargo Bay
- [ ] Cargo Office
- [ ] Delivery Office
- [ ] Mining Dock
- [ ] Quartermaster's Office

### Science
- [ ] Research Division
- [ ] Experimental Lab
- [ ] Research and Development Lab
- [ ] Research Director's Office
- [ ] Robotics Lab
- [ ] Server Room
- [ ] Toxins Lab
- [ ] Toxins Test Chamber
- [ ] Testing Lab
- [ ] Xenobiology Lab

### Engineering
- [ ] Engineering
- [ ] Atmospherics
- [ ] Auxilliary Base Construction
- [ ] Chief Engineer's Office
- [ ] Construction Area
- [ ] Electrical Maintenance
- [ ] Gravity Generator Room
- [ ] Solars
- [ ] Thermo-Electric Generator
- [ ] Technical Storage
- [ ] Telecommunications
- [ ] Vacant Office A
- [ ] Vacant Office B

### Security
- [ ] Armory
- [ ] Brig
- [ ] Courtroom
- [ ] Detective's Office
- [ ] Interrogation
- [ ] Head of Security's Office
- [ ] Law Office
- [ ] Prison Wing
- [ ] Labor Camp
- [ ] Security Office
- [ ] Security Posts
- [ ] Warden's Office

### Command
- [ ] AI Satellite
- [ ] AI Upload
- [ ] Bridge
- [ ] Captain's Quarters
- [ ] Conference Room
- [ ] E.V.A.
- [ ] Gateway
- [ ] Head of Personnel's Office
- [ ] Teleporter
- [ ] Vault

### Upkeep
- [ ] Custodial Closet
- [ ] Incinerator
- [ ] Maintenance
- [ ] Waste Disposal

### Outside
- [ ] Abandoned Satellite
- [ ] Central Command
- [ ] Derelict
- [ ] White Ship
- [ ] Mining Station
- [ ] Lavaland
- [ ] Space
